/**
 * RELEASED INVENTORY — the one place that controls which residences are public.
 * ============================================================================
 *
 * The developer releases inventory in phases. Units not listed here are HIDDEN
 * from the website but are NOT deleted: their data, specs, floor plans and
 * artwork all stay in the project, ready to be switched back on.
 *
 * TO CHANGE WHAT IS VISIBLE, EDIT src/data/released.json AND NOTHING ELSE.
 * (It is JSON rather than TypeScript so the Astro config can read the same
 * list when it builds the sitemap — one source of truth, no duplication.)
 *
 *   Show a unit again → add its number, e.g. '502'
 *   Hide a unit       → remove its number
 *
 * Then run `npm run build`. Every surface follows automatically: the mega-panel
 * navigation, the home inventory strip, the Residences index and its filters,
 * the floor-plan families, prev/next paging, the sitemap, and which unit pages
 * get generated at all.
 *
 * Use the unit NUMBER exactly as it appears in the slug — '302', '401', '701'.
 *
 * NOTE ON PAGE GENERATION: only released residences get a page. This used to
 * build all 27 and leave the hidden ones unlinked, noindex and out of the
 * sitemap but still reachable by direct URL, so one could be sent to a broker
 * ahead of release. That is no longer true, and the reason is that a hidden
 * page still served its asking price to anyone who guessed the URL.
 *
 * Removing a number from the list now takes the residence off the site
 * completely: its page 404s, and its floor-plan PDF and drawing stop being
 * built along with it — those are generated by routes under src/pages/
 * floorplans/ which read the released set, rather than sitting in public/
 * where everything is copied out whether or not it is wanted.
 *
 * Nothing is DELETED by a withdrawal. Every file stays in the project and the
 * residence returns in full when its number goes back in the list.
 *
 * If you need to show an unreleased residence to a broker, send them a build
 * preview or a PDF directly — do not reach for a URL that no longer exists.
 *
 * The building has 27 residences in total. That figure is a fact about the
 * building and appears in the marketing copy; it is independent of how many are
 * currently released, and it does not change when this list does.
 */
import config from './released.json';

export const RELEASED_UNIT_NUMBERS: string[] = config.releasedUnitNumbers;

/** Every residence in the building, released or not. A brand fact. */
export const TOTAL_RESIDENCES: number = config.totalResidences;
